##
## ATOS PROJECT 2022
## MAKEFILE
## File description:
## Wow, such make, much file!
##

SLURM_INC_DIR		=	/root/SLURM/slurm.build
IBMAD_INC_DIR		=	/usr/include/infiniband/
LIB_SLURM			=	/usr/lib64/slurm
LIB_SLURM_FULL		=	slurmfull